"use client"

import { Box, Flex } from "@chakra-ui/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
    {children}
    </div>
  );
}
